/* Name: Tyler Clark
*  Date: 10/31/2021
*  CMSC 430 Project 1
*  This file contains the enumerated type definition for tokens */

enum Tokens {RELOP = 256, ADDOP, MULOP, ANDOP, BEGIN_, BOOLEAN, END, ENDREDUCE,
	FUNCTION, INTEGER, IS, REDUCE, RETURNS, IDENTIFIER, INT_LITERAL, ARROW, CASE,
	ELSE, ENDCASE, ENDIF, IF, OTHERS, REAL, THEN, WHEN, OROP, NOTOP, REMOP, EXPOP, 
	REAL_LITERAL, BOOL_LITERAL};
